name: Push CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Test
        env:
          CI: true
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Build Package
        run: npm run build
